baseurl: "/"
title: "David Freilich"
page_load_js: "assets/js/main.js"
params:
  layout_style: overflow
  palette: blue
  header:
    title: "David Freilich"
    tagline: Software/ML Engineer
    profile_img: images/avatar.jpg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
      - text: Check it out on Github
        url: https://github.com/dfreilich/dfreilich.github.io
        new_window: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
